<h3>Courses</h3>
<table class="uk-table">
    <thead>
        <tr>
            <th colspan="4"></th>
            <th colspan="2">Rating</th>
        </tr>
        <tr>
            <th></th>
            <th>Par</th>
            <th>Distance</th>
            <th>Location</th>
            <th>Scratch</th>
            <th>Slope</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
            <tr>   
                <td><a href="/course/{{ course.post_name }}">{{ course.post_title }}</a></td>
                <td>{{ course.par }}</td>
                <td><?php print_r($course->distance()); ?></td>
                <td><?php print_r($course->angle()); ?></td>
                <td><?php print_r($course->scratch); ?></td>
                <td><?php print_r($course->slope); ?></td>
            </tr>
        {% endfor %}
    </tbody>
</table>