<style>
    ul.uk-pagination {
        margin-top: 20px; }
    
     ul.uk-pagination li a{
         text-shadow: none;
         color: #fff;
         background: #005391;
         border-radius: 0;
         font-weight: 300;
     }

     ul.uk-pagination li.uk-active span, ul.uk-pagination li:hover a{
         text-shadow: none;
         color: #005391;
         border-color: #005391;
         background: #fff;
         border-radius: 0;
     }    

         ul.uk-pagination li.uk-disabled span{
         text-shadow: none;
         color: #005391;
         border-color: #005391;
         background: #fff;
         border-radius: 0;
         font-weight: 300;
     }    
</style>

<div class="uk-grid">
    <div class="uk-width-1-1">
        <ul class="uk-pagination uk-pagination-left">
            {% if page.current != 1 %} 
                <li><a href="/{{ pagination }}/{{ page.before }}">Previous</a></li>
            {% endif %}
            {% for i in 1..page.total_pages %}
                {% if i is page.current %} 
                    <li class="uk-active"><span>{{ i }}</span></li>
                {% else %}
                    <li><a href="/{{ pagination }}/{{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.current != page.total_pages %} 
                <li><a href="/{{ pagination }}/{{ page.next }}">Next</a></li>
            {% endif %}
        </ul>
    </div>
</div>