<style>
    a.heading {
        font-weight: 700;
        text-decoration: none;
        text-transform: uppercase;
        font-size: 20px;
        margin-bottom: 5px;
        display: block; }
    
     span.date {
        margin: 5px 0;
        display:block;
        font-weight: 300;
        font-size: 15px;
        text-decoration: none;
        text-transform: uppercase;
        color: #888; }
    
     span.category a {
        display: inline-block;
        margin: 5px 0;
        font-weight: 300;
        font-size: 12px;
        text-decoration: none;
        padding: 2px 4px;
        text-transform: uppercase;
        color: #fff;
        background: #005391; }
    
     span.tag a {
        font-size: 12px;
        text-decoration: none;
        padding: 2px 4px;
        text-transform: uppercase;
        color: #005391;
        background: #d8d8d8; }
    
</style>

<a class="heading">{{ post.post_title }}</a>
<span class="date">{{ post.date }}</span>
    {% set meta_data = post.get_tags() %}
    {% if meta_data['category'] is iterable  %}
        {% for tag in meta_data['category'] %}
            <span class="category"><a href="/tag/<?php echo $tag->slug; ?>"><?php echo $tag->name; ?></a></span>
        {% endfor %}
    {% endif %}

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="addthis_sharing_toolbox"></div>
<p><iframe width="100%" height="450" src="//www.youtube.com/embed/{{ post.video_url }}" frameborder="0" allowfullscreen></iframe></p>

    {% if meta_data['tag'] is iterable  %}
        {% for tag in meta_data['tag'] %}
            <span class="tag"><a href="/tag/<?php echo $tag->slug; ?>"><?php echo $tag->name; ?></a></span>
        {% endfor %}
    {% endif %}