<!DOCTYPE html>
<html>
    <head profile="http://www.w3.org/2005/10/profile">
        <link rel="icon" type="image/png" href="/img/favicon.png">
        <title>{% if(title is defined) %}{{ title }}{% else %}AGATOUR{% endif %}</title>
        <meta property="og:title" content="{% if(title is defined) %}{{ title }}{% else %}AGATOUR{% endif %}" />        
        <meta property="og:image" content="{% if(image is defined) %}{{ image }}{% endif %}" />
        <meta property="og:description" content="{% if(description is defined) %}{{ description }}{% else %}Official Website of the AGA Tour.{% endif %}" />

        {{ stylesheet_link('css/uikit.almost-flat.css') }}
        {{ stylesheet_link('css/style.css') }}

        {{ javascript_include('http://code.jquery.com/jquery-2.1.1.min.js') }}
        {{ javascript_include('js/uikit.min.js') }}

        {{ partial("analytics") }}
        {{ partial("addthis") }}
    </head>
    <body>
        <div class="uk-container uk-container-center uk-margin-top uk-margin-large-bottom">
            <div class="uk-grid uk-margin-top uk-margin-bottom uk-hidden-small">
                <div class="uk-width-2-10 logo">{{ image('img/logo.png',  "alt" : "AGA Tour") }}</div>
                <div class="uk-width-5-10">...</div>
                <div class="uk-width-3-10 social">
                    <a target="_blank" href="http://facebook.com/agatourgolf" class="uk-icon-medium uk-icon-facebook"></a>
                    <a target="_blank" href="http://twitter.com/agatour_golf" class="uk-icon-medium uk-icon-twitter"></a>
                    <a target="_blank" href="http://youtube.com/agatour" class="uk-icon-medium uk-icon-youtube"></a>
                    <a target="_blank" href="http://instagram.com/agatour" class="uk-icon-medium uk-icon-instagram"></a>
                </div>
            </div>
            {{ partial("theme/nav") }}
            <div class="page-content uk-margin-top uk-margin-large-bottom">
                <div class="uk-grid">
                    {% if fullwidth is defined %}
                        <div class="uk-width-1-1">{{ content() }}</div>
                    {% else %}
                        <div class="uk-width-large-7-10 uk-width-small-1-1">{{ content() }}</div>
                        <div class="uk-width-3-10 uk-hidden-small">{{ partial("theme/sidebar") }}</div>
                    {% endif %}
				</div>
            </div>								

            <div class="uk-grid uk-margin-top uk-margin-bottom uk-text-center">
                <div class="uk-width-1-1 copyright">
				    &copy; 2012-2014 AGA TOUR, Inc | All Rights Reserved.<br>
                    AGA TOUR, Nandos Cup, and the AGA Ranking System are registered trademarks.<br>
				</div>
            </div>
        </div>
    </body>
</html>